Windows support

diff --git a/vir b/vir
--- a/vir
+++ b/vir
@@ -1,36 +1,45 @@
 #!/usr/bin/env bash
 
 build_release() {
-  if [[ $(uname) != "Linux" ]]; then
+  if [ $(uname) != "Linux" -a $(uname) != "MINGW64_NT-10.0" ]; then
     echo "You are running $(uname), not Linux - aborting release"
     exit 1
   fi
 
-  local branch_name=$(git rev-parse --abbrev-ref HEAD)
-
-  while read line
-  do
+  if [[ -z "$MANUAL_VERSION" ]]; then
+    while read line
+    do
       local prev_build_no=$line
-  done < "deployment/build_no"
+    done < "deployment/build_no"
 
-  if [[ $RERELEASE -eq 0 ]]; then
-    echo Updating Release Number
-    local build_no=$((prev_build_no + 1))
+    if [[ $RERELEASE -eq 0 ]]; then
+      echo Updating Release Number
+      local build_no=$((prev_build_no + 1))
+    else
+      local build_no=$prev_build_no
+    fi
+
+    while read line
+    do
+      local major=$line
+    done < "deployment/major_ver"
+
+    while read line
+    do
+      local minor=$line
+    done < "deployment/minor_ver"
   else
-    local build_no=$prev_build_no
+    IFS="." read major minor build_no <<< "$MANUAL_VERSION"
   fi
 
-  while read line
-  do
-      local major=$line
-  done < "deployment/major_ver"
+  if [[ -z $MANUAL_VERSION_LABEL ]]; then
+    local branch_name=$(git rev-parse --abbrev-ref HEAD)
+    local release="v$major.$minor.$build_no-$branch_name"
+  else
+    local release="$MANUAL_VERSION_LABEL"
+  fi
 
-  while read line
-  do
-      local minor=$line
-  done < "deployment/minor_ver"
-
-  local release="v$major.$minor.$build_no-$branch_name"
+  echo "Version $major.$minor.$build_no: $release"
 
   # Update version on disc even if we're re-releasing
   # because we might have switched branch in which case
@@ -44,8 +53,11 @@ build_release() {
       fi
   fi
 
-  if [[ $RERELEASE -eq 0 ]]; then
-    echo $build_no > "deployment/build_no"
+  if [[ $RERELEASE -eq 0 ]] || [[ -n $MANUAL_VERSION ]] || [[ -n $MANUAL_VERSION_LABEL ]]; then
+    echo "$major" > "deployment/major_ver"
+    echo "$minor" > "deployment/minor_ver"
+    echo "$build_no" > "deployment/build_no"
+    echo "$release" > "deployment/label"
   fi
 
   echo Building Release $release
@@ -58,7 +70,9 @@ build_release() {
   if [[ -d apps ]]; then
       if [[ -z $RELEASE_APP ]]; then
           echo "Releasing all apps"
-          ls -l apps | awk '{print $9}' | xargs -L 1 rebar3 release -n
+          for app in $(ls apps/); do
+              rebar3 release -n $app
+          done
       else
           echo "Releasing $RELEASE_APP"
           rebar3 release $RELEASE_APP
@@ -68,16 +82,19 @@ build_release() {
       rebar3 release
   fi
 
-  if [[ $RERELEASE -eq 1 ]]; then
-    echo "Re-release, not bumping versions"
-  else
+  if [[ $RERELEASE -eq 0 ]] || [[ -n $MANUAL_VERSION ]] || [[ -n $MANUAL_VERSION_LABEL ]]; then
     # TODO: Deal with native deps if there are any
     echo Making BoM and updating Git with new release tag
     build_bill_of_materials $release "deployment/bill_of_materials"
+  fi
 
+  if [[ $RERELEASE -eq 1 ]]; then
+    echo "Re-release, not updating version files in git"
+  else
     git add deployment/build_no
     git add deployment/bill_of_materials.txt
     git add deployment/bill_of_materials.info
+    git add deployment/label
 
     ls -d apps/*/include | xargs -n 1 git add
 
@@ -108,7 +125,7 @@ build_bill_of_materials() {
   echo >> $logtotxt
   echo -e "base\t$release\t$(git remote -v | head -1 | awk  '{print $2}')\t$(git rev-parse HEAD)" > $logtoinfo
 
-  local all_deps=$(find deps -mindepth 1 -maxdepth 1 -type d | sort)
+  local all_deps=$(find _build/default/lib -mindepth 1 -maxdepth 1 -type d | sort)
 
   for dep in $all_deps ; do
     pushd $dep > /dev/null
@@ -148,7 +165,11 @@ build_tar() {
   local app=$(basename $app_dir)
   local working_dir=$(dirname $app_dir)
   local tar_dir="${app}_$git_tag"
-  local tar_name="${tar_dir}.tar.gz"
+  if [ $(uname) == "MINGW64_NT-10.0" ]; then
+    local tar_name="${tar_dir}.zip"
+  else
+    local tar_name="${tar_dir}.tar.gz"
+  fi
   local autorun_name="$releases_folder/install-${tar_name%.tar.gz}"
 
   if [[ -f ./apps/$app/release-files/pre_tar.sh ]]; then
@@ -160,19 +181,29 @@ build_tar() {
   rm -f $tar_name
 
   pushd $working_dir > /dev/null
-  mv $app $tar_dir
-  tar cfz $releases_folder/$tar_name $tar_dir  || { echo "Tar failed"; exit 1; }
-  mv $tar_dir $app
+  if [ $(uname) == "MINGW64_NT-10.0" ]; then
+    zip -q -9 -r $releases_folder/$tar_name $app || { echo "Zip failed"; exit 1; }
+  else
+    mv $app $tar_dir
+    tar cfz $releases_folder/$tar_name $tar_dir  || { echo "Tar failed"; exit 1; }
+    mv $tar_dir $app
+  fi
+
   popd > /dev/null
 
   if [[ -f ./apps/$app/release-files/post_tar.sh ]]; then
     echo Running post-tar script for $app
     ./apps/$app/release-files/post_tar.sh $tar_name $git_tag
   else
-    cat $SOURCEDIR/autoextract.sh $releases_folder/$tar_name > $autorun_name
+    if [ $(uname) != "MINGW64_NT-10.0" ]; then
+        cat $SOURCEDIR/autoextract.sh $releases_folder/$tar_name > $autorun_name
+        chmod +x $autorun_name
+        echo done
+    fi
+  fi
+
+  if [ $(uname) != "MINGW64_NT-10.0" ]; then
     rm $releases_folder/$tar_name
-    chmod +x $autorun_name
-    echo done
   fi
 }
 
@@ -197,7 +228,7 @@ usage() {
       echo
       ;;
     "release")
-      echo "vir release [-d] [-r] [-a <app_name>]"
+      echo "vir release [-d] [-r] [-a <app_name>] [-v <major>.<minor>.<build>] [-l <build_label>]"
       echo "---"
       echo "   Creates a self extracting tar of each application and updates the versions (if available)"
       echo "   -d is a dirty release (don't build deps, don't clean all)"
@@ -205,6 +236,10 @@ usage() {
       echo "   -r is used to re-release whatever the current version number is, so the current version number"
       echo "   is used without being incremented. Use with care."
       echo "   -a app_name just does the release / tar of app_name"
+      echo "   -v 1.0.0 uses the provided version number rather than generating a new one. The provided version"
+      echo "      version will be written to the deployment/ files as normal"
+      echo "   -l v1.0.0-blah uses the specified build label rather than generating one. The provided label"
+      echo "      will be written to a shared version.hrl as normal"
       echo
       ;;
     *)
@@ -232,6 +267,8 @@ DIRTYRELEASE=0
 RERELEASE=0
 COOKIE='cookie'
 KERNEL='-kernel inet_dist_listen_min 9100 inet_dist_listen_max 9105 +K true +A 10'
+MANUAL_VERSION=
+MANUAL_VERSION_LABEL=
 
 check_vir_path() {
   if [[ ! -d $SOURCEDIR ]]; then
@@ -254,7 +291,7 @@ case "$COMMAND" in
     ;;
   "release")
     RELEASE_APP=
-    while getopts ":dra:" option; do
+    while getopts ":dra:v:l:" option; do
       case "$option" in
         d)
           DIRTYRELEASE=1
@@ -264,6 +301,12 @@ case "$COMMAND" in
           ;;
         a)
           RELEASE_APP=$OPTARG
+          ;;
+        v)
+          MANUAL_VERSION=$OPTARG
+          ;;
+        l)
+          MANUAL_VERSION_LABEL=$OPTARG
           ;;
         ?)
           echo "Error: unknown option -$OPTARG"
